# Generated by Django 3.2.4 on 2022-01-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cityevents',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField(default='lucknow', max_length=50)),
                ('description', models.TextField(null=True)),
                ('event_pic', models.ImageField(max_length=1000, null=True, upload_to='camp/eventimg')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('query', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=45)),
                ('CampName', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('FeedbackText', models.TextField()),
                ('Rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('SummerCamp_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=45)),
                ('CampName', models.CharField(max_length=50)),
                ('OwnerName', models.CharField(max_length=40)),
                ('CampMailId', models.CharField(max_length=50)),
                ('CampPhone', models.CharField(max_length=10)),
                ('CampAddress', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDetails',
            fields=[
                ('ProgramId', models.AutoField(primary_key=True, serialize=False)),
                ('ProgramName', models.CharField(max_length=30)),
                ('Duration', models.CharField(max_length=20)),
                ('Fees', models.CharField(max_length=30)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Description', models.TextField()),
                ('AgeGroup', models.CharField(max_length=20)),
                ('SummerCamp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.organizer')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Description',
            fields=[
                ('job_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('postname', models.CharField(max_length=50)),
                ('NoOfSeats', models.IntegerField()),
                ('LastDateToApply', models.DateField()),
                ('PostDate', models.DateField()),
                ('JobDescription', models.TextField()),
                ('SummerCamp_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.organizer')),
            ],
        ),
    ]
