# Generated by Django 3.2.4 on 2022-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='SummerCamp_Id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
